### ISSUE TITLE
howto: Use markdown-it plugins with this?

### ISSUE THREAD

**Issue by bishless** [mayo/metalsmith-markdownit#1]
How can I use markdown-it plugins (i.e. footnotes, mark, or emoji) w/ this metalsmith plugin?

**Comment by mayo** [comment]
@bishless Sorry, I didn't see this till now. You can get access to the markdown-it parser by instantiating metalsmith-markdownit first, and then calling `.parser` on it. I added a test case for markdown-it-abbr plugin.

Eg:

```
var Metalsmith = require('metalsmith');
var markdown = require('..');

var md = markdown('default');

md.parser.use(require('markdown-it-abbr'));

Metalsmith('test/fixtures/plugin')
  .use(md)
  .build(function(err){
    if (err) return done(err);
    equal('test/fixtures/plugin/expected', 'test/fixtures/plugin/build');
    done();
  });
```

`md.parser` in the above example gives you an instance of markdown-it, so with that, you can work off the examples on markdown-it page or any of its plugins.
