### ISSUE TITLE
Parsed file extensions don't change when passed in option ?

### ISSUE THREAD

**Issue by ghost** [mayo/metalsmith-markdownit#16]
I'm trying to change the default 'html' output extension through this option:

.use(markdown('commonmark', {
    plugin: {
      extension: 'njk' 
    }
}))

but the output is still .html
I am using it wrong?

**Comment by ghost** [comment]
I have
const markdown = require('metalsmith-markdownit')
of course

**Comment by dsoulayrol** [comment]
Hello.
If you rely on the 0.4.0 version delivered by NPM, then I think you have the problem I just encountered. Please see #17.

**Comment by mayo** [comment]
@spam-man It should work now in 0.5.0. As @dsoulayrol pointed out, the 0.4.0 release was broken.
