### ISSUE TITLE
Mismatch between the repository and NPM versions

### ISSUE THREAD

**Issue by dsoulayrol** [mayo/metalsmith-markdownit#17]
Hello.

I wanted to use one plugin option (namely the `extension` option) and nothing happened. Checking the copy of the plugin in my `node_modules` directory, I realised it did not match the master branch version, and there was no handling of plugin options at all.

I tried to update from NPM, but I have the latest version ; 0.4.0. Then, I found something strange. The plugin in the NPM package is correctly labeled 0.4.0, but its code matches the one in the 0.4.0 tag, where the version is... 0.3.0.

*In fine*, the handling of plugin parameters seems to never have been released, and the existing version numbers are disturbing. Could it be possible to release a new version with all the up-to-date features?

Thanks for your work.

**Comment by mayo** [comment]
@dsoulayrol Good eye, thanks! Not sure how that happened, but I just pushed out 0.5.0 that's fixed up plus update to markdown-it 8.x that I forgot to push out earlier.
