### ISSUE TITLE
Not adding plugin correctly

### ISSUE THREAD

**Issue by marr** [mayo/metalsmith-markdownit#5]
Hi,
I am trying to use this with the markdown-it-footnote plugin. The following build.js (as suggested in the readme), does not work:

```
var Metalsmith = require('metalsmith');
var layouts = require('metalsmith-layouts');
var markdown = require('metalsmith-markdownit');
var sass = require('metalsmith-sass');

Metalsmith(__dirname)
  //.use(layouts('handlebars'))
  .use(markdown('default', { footnote: true }))
  .use(sass({ outputDir: 'css' }))
  .build(function(err) {
    if (err) {
      throw err;
    }
  });
```

This however, does:

```
var Metalsmith = require('metalsmith');
var layouts = require('metalsmith-layouts');
var markdown = require('metalsmith-markdownit');
var sass = require('metalsmith-sass');
var footnote = require('markdown-it-footnote');

var md = markdown('default', {
  footnote: true
});
md.parser.use(footnote);
Metalsmith(__dirname)
  .use(md)
  .use(sass({ outputDir: 'css' }))
  .build(function(err) {
    if (err) {
      throw err;
    }
  });
```

Can you help me figure out whats going on there?

**Comment by mayo** [comment]
The second way is the correct way to use it. The first way you have doesn't instantiate the footnote plugin, and `footnote` is not a valid markdown-it option, as per https://markdown-it.github.io/markdown-it/#MarkdownIt.new.

In the second case you don't need the `footnote: true` at all, it's the `.use(footnote)` that makes it work.

**Comment by marr** [comment]
Ok Mayo, it was unclear from the readme that the second way is the only supported way to use markdown-it plugins. Do you need a PR for that?
