### ISSUE TITLE
Markdown is showing as html with handlebars?

### ISSUE THREAD

**Issue by oneuxco** [mayo/metalsmith-markdownit#7]
When I create a page, and try calling that collection with handlebars, for example:

```
{{#each collections.posts}}
        <h1>{{this.title}}</h1>
        <article>{{this.contents}}</article>
    {{/each}}
```

It prints everything with html, so the page literally shows

```
Blog post
<p>my content</p>
```

Any thoughts on how to fix this?

**Comment by mayo** [comment]
Is this maybe an issue with handlebars escaping html content on purpose? See if http://stackoverflow.com/questions/15807799/node-js-and-handlebars-html-compiled-is-escaped helps
